var searchData=
[
  ['scoped_5fallocator_5fadaptor_1636',['scoped_allocator_adaptor',['http://en.cppreference.com/w/cpp/memory/scoped_allocator_adaptor.html',1,'std']]],
  ['seconds_1637',['seconds',['http://en.cppreference.com/w/cpp/chrono/duration.html',1,'std::chrono']]],
  ['seed_5fseq_1638',['seed_seq',['http://en.cppreference.com/w/cpp/numeric/random/seed_seq.html',1,'std']]],
  ['sentry_1639',['sentry',['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'istringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'istream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'ostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'ostrstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'wfstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'wistringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'basic_fstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'wofstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'wstringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'ofstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'wiostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'strstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'basic_iostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'ifstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'fstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'ostringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'wostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'basic_stringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'basic_ostringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'wostringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'istrstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'basic_ostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'basic_istringstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'basic_istream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'iostream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'wistream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'basic_ifstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_istream/sentry.html',1,'wifstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'basic_ofstream::sentry'],['http://en.cppreference.com/w/cpp/io/basic_ostream/sentry.html',1,'stringstream::sentry']]],
  ['session_5fneeded_5ferror_1640',['Session_needed_error',['../classge211_1_1exceptions_1_1_session__needed__error.html',1,'ge211::exceptions']]],
  ['set_1641',['set',['http://en.cppreference.com/w/cpp/container/set.html',1,'std']]],
  ['shared_5ffuture_1642',['shared_future',['http://en.cppreference.com/w/cpp/thread/shared_future.html',1,'std']]],
  ['shared_5flock_1643',['shared_lock',['http://en.cppreference.com/w/cpp/thread/shared_lock.html',1,'std']]],
  ['shared_5fptr_1644',['shared_ptr',['http://en.cppreference.com/w/cpp/memory/shared_ptr.html',1,'std']]],
  ['shared_5fptr_3c_20const_20std_3a_3astring_20_3e_1645',['shared_ptr&lt; const std::string &gt;',['http://en.cppreference.com/w/cpp/memory/shared_ptr.html',1,'std']]],
  ['shared_5fptr_3c_20impl_5f_20_3e_1646',['shared_ptr&lt; Impl_ &gt;',['http://en.cppreference.com/w/cpp/memory/shared_ptr.html',1,'std']]],
  ['shared_5fptr_3c_20mix_5fchunk_20_3e_1647',['shared_ptr&lt; Mix_Chunk &gt;',['http://en.cppreference.com/w/cpp/memory/shared_ptr.html',1,'std']]],
  ['shared_5fptr_3c_20mix_5fmusic_20_3e_1648',['shared_ptr&lt; Mix_Music &gt;',['http://en.cppreference.com/w/cpp/memory/shared_ptr.html',1,'std']]],
  ['shared_5ftimed_5fmutex_1649',['shared_timed_mutex',['http://en.cppreference.com/w/cpp/thread/shared_timed_mutex.html',1,'std']]],
  ['shuffle_5forder_5fengine_1650',['shuffle_order_engine',['http://en.cppreference.com/w/cpp/numeric/random/shuffle_order_engine.html',1,'std']]],
  ['sig_5fatomic_5ft_1651',['sig_atomic_t',['http://en.cppreference.com/w/cpp/utility/program/sig_atomic_t.html',1,'std']]],
  ['size_5ft_1652',['size_t',['http://en.cppreference.com/w/cpp/types/size_t.html',1,'std']]],
  ['smatch_1653',['smatch',['http://en.cppreference.com/w/cpp/regex/match_results.html',1,'std']]],
  ['sound_5feffect_1654',['Sound_effect',['../classge211_1_1audio_1_1_sound__effect.html',1,'ge211::audio']]],
  ['sound_5feffect_5fhandle_1655',['Sound_effect_handle',['../classge211_1_1audio_1_1_sound__effect__handle.html',1,'ge211::audio']]],
  ['sprite_1656',['Sprite',['../classge211_1_1sprites_1_1_sprite.html',1,'ge211::sprites']]],
  ['sprite_5fset_1657',['Sprite_set',['../classge211_1_1_sprite__set.html',1,'ge211']]],
  ['sregex_5fiterator_1658',['sregex_iterator',['http://en.cppreference.com/w/cpp/regex/regex_iterator.html',1,'std']]],
  ['sregex_5ftoken_5fiterator_1659',['sregex_token_iterator',['http://en.cppreference.com/w/cpp/regex/regex_token_iterator.html',1,'std']]],
  ['ssub_5fmatch_1660',['ssub_match',['http://en.cppreference.com/w/cpp/regex/sub_match.html',1,'std']]],
  ['stack_1661',['stack',['http://en.cppreference.com/w/cpp/container/stack.html',1,'std']]],
  ['state_5ftype_1662',['state_type',['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'codecvt_byname::state_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'codecvt_utf16::state_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'codecvt::state_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'codecvt_utf8_utf16::state_type'],['http://en.cppreference.com/w/cpp/locale/codecvt.html',1,'codecvt_utf8::state_type']]],
  ['steady_5fclock_1663',['steady_clock',['http://en.cppreference.com/w/cpp/chrono/steady_clock.html',1,'std::chrono']]],
  ['streambuf_1664',['streambuf',['http://en.cppreference.com/w/cpp/io/basic_streambuf.html',1,'std']]],
  ['streamoff_1665',['streamoff',['http://en.cppreference.com/w/cpp/io/streamoff.html',1,'std']]],
  ['streampos_1666',['streampos',['http://en.cppreference.com/w/cpp/io/fpos.html',1,'std']]],
  ['streamsize_1667',['streamsize',['http://en.cppreference.com/w/cpp/io/streamsize.html',1,'std']]],
  ['string_1668',['string',['http://en.cppreference.com/w/cpp/string/basic_string.html',1,'std']]],
  ['string_5ftype_1669',['string_type',['http://en.cppreference.com/w/cpp/locale/messages.html',1,'messages::string_type'],['http://en.cppreference.com/w/cpp/locale/numpunct.html',1,'numpunct_byname::string_type'],['http://en.cppreference.com/w/cpp/locale/moneypunct.html',1,'moneypunct_byname::string_type'],['http://en.cppreference.com/w/cpp/locale/money_put.html',1,'money_put::string_type'],['http://en.cppreference.com/w/cpp/locale/collate.html',1,'collate_byname::string_type'],['http://en.cppreference.com/w/cpp/locale/messages.html',1,'messages_byname::string_type'],['http://en.cppreference.com/w/cpp/locale/collate.html',1,'collate::string_type'],['http://en.cppreference.com/w/cpp/locale/moneypunct.html',1,'moneypunct::string_type'],['http://en.cppreference.com/w/cpp/locale/money_get.html',1,'money_get::string_type'],['http://en.cppreference.com/w/cpp/locale/numpunct.html',1,'numpunct::string_type']]],
  ['stringbuf_1670',['stringbuf',['http://en.cppreference.com/w/cpp/io/basic_stringbuf.html',1,'std']]],
  ['stringstream_1671',['stringstream',['http://en.cppreference.com/w/cpp/io/basic_stringstream.html',1,'std']]],
  ['strstream_1672',['strstream',['http://en.cppreference.com/w/cpp/io/strstream.html',1,'std']]],
  ['strstreambuf_1673',['strstreambuf',['http://en.cppreference.com/w/cpp/io/strstreambuf.html',1,'std']]],
  ['student_5ft_5fdistribution_1674',['student_t_distribution',['http://en.cppreference.com/w/cpp/numeric/random/student_t_distribution.html',1,'std']]],
  ['sub_5fmatch_1675',['sub_match',['http://en.cppreference.com/w/cpp/regex/sub_match.html',1,'std']]],
  ['subtract_5fwith_5fcarry_5fengine_1676',['subtract_with_carry_engine',['http://en.cppreference.com/w/cpp/numeric/random/subtract_with_carry_engine.html',1,'std']]],
  ['system_5fclock_1677',['system_clock',['http://en.cppreference.com/w/cpp/chrono/system_clock.html',1,'std::chrono']]],
  ['system_5ferror_1678',['system_error',['http://en.cppreference.com/w/cpp/error/system_error.html',1,'std']]]
];
